apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-oyen-r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-oyen-r
  template:
    metadata:
      labels:
        app: gs-oyen-r
    spec:
      containers:
      - name: gs-oyen-r
        image: gs-oyen-r:latest
